// <auto-generated />
namespace BankService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class CommandUsername : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CommandUsername));
        
        string IMigrationMetadata.Id
        {
            get { return "201912121341149_Command-Username"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
